### PR TITLE
Bug 1975379: Use hard requirement for anti-affinity rules on both console's deployments

### PR DESCRIPTION
**Pull request by jhadvig**
Use `requiredDuringSchedulingIgnoredDuringExecution` for anti-affinity rules on both console's deployments.
The label selectors for console deployment will be:
`"app": "console", "component": "ui"`
The label selectors for downloads deployment will be:
`"app": "console", "component": "downloads"`

/assign @spadgett

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by spadgett** [comment]
Hm, looks like this prevents console rollout:

```yaml
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-06-24T16:59:02Z"
    message: '0/6 nodes are available: 3 node(s) didn''t match Pod''s node affinity/selector,
      3 node(s) didn''t match pod affinity/anti-affinity rules, 3 node(s) didn''t
      match pod anti-affinity rules.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
```

/lgtm cancel

**Comment by spadgett** [comment]
I have a feeling the problem is with rolling deployments since we'll have more than the normal number of replicas. If there are ever more than 3, they'll fail to schedule. We probably need to look at max surge and max unavailable if we want to make this a hard requirement.

**Comment by jhadvig** [comment]
@spadgett I've added additional commit that update podAntiAffinity rules and explicitly specifies deployment strategy and its `maxSurge` and `maxUnavailability` 🤞

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
