### PR TITLE
Bug 1764316: Backport metrics_test.go [Release-4.2]

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Ensure the `console_url` is available on the `/metrics` endpoint.

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
/retest

```
     metrics_test.go:185: route for metrics: https://metrics-openshift-console-operator.apps.ci-op-q5nfip1p-536f7.origin-ci-int-aws.dev.rhcloud.com/metrics
    metrics_test.go:191: route to /metrics: (https://metrics-openshift-console-operator.apps.ci-op-q5nfip1p-536f7.origin-ci-int-aws.dev.rhcloud.com/metrics)
    metrics_test.go:58: fetching metrics url.... https://metrics-openshift-console-operator.apps.ci-op-q5nfip1p-536f7.origin-ci-int-aws.dev.rhcloud.com/metrics
    metrics_test.go:60: fetching /metrics data...
    metrics_test.go:97: http error: 503 Service Unavailable 
```
Hmm.

**Comment by jhadvig** [comment]
Same issue :( Dont think its a flake.

**Comment by benjaminapetersen** [comment]
Yup, several issues around the route:

```
# early on, but resolves
E1205 04:27:09.933682       1 status.go:71] RouteSyncProgressing FailedHost route is not available at canonical host []
E1205 04:27:09.937611       1 status.go:118] status update error: Operation cannot be fulfilled on consoles.operator.openshift.io "cluster": the object has been modified; please apply your changes to the latest version and try again
E1205 04:27:09.937638       1 controller.go:129] {Console Console} failed with: route is not available at canonical host []
# ...
"openshift-config-managed" "console-public"}]
E1205 04:43:22.506025       1 status.go:71] RouteSyncProgressing InvalidRoute route is invalid, correcting route state
E1205 04:43:22.512379       1 controller.go:129] {Console Console} failed with: route is invalid, correcting route state
# ...
I1205 04:43:23.204989       1 event.go:209] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"openshift-console-operator", Name:"console-operator", UID:"72277379-1717-11ea-86c3-0ac54aa6d1e1", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'OperatorStatusChanged' Status for clusteroperator/console changed: Progressing message changed from "RouteSyncProgressing: route is invalid, correcting route state" to "SyncLoopRefreshProgressing: Changes made during sync updates, additional sync expected."
```

**Comment by benjaminapetersen** [comment]
Closing htis and the bug.  The effort & risk for a 4.2 backport is too high (even if it is just a test).

**Pull request closed without merging**
