### PR TITLE
OCPBUGS-39357, CONSOLE-4055: Vendor API changes

### PR DESCRIPTION
**Pull request by jhadvig**
/assign @spadgett

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by jhadvig** [comment]
```
level=error msg=failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed provisioning resources after infrastructure ready: error creating DNS records: failed to create public record set: PUT https://management.azure.com/subscriptions/d38f1e38-4bed-438e-b227-833f997adf6a/resourceGroups/os4-common/providers/Microsoft.Network/dnsZones/ci.azure.devcluster.openshift.com/CNAME/api.ci-op-kpgfgb07-ff149
level=error msg=--------------------------------------------------------------------------------
level=error msg=RESPONSE 409: 409 Conflict
level=error msg=ERROR CODE: Conflict
level=error msg=--------------------------------------------------------------------------------
level=error msg={
level=error msg=  "code": "Conflict",
level=error msg=  "message": "You have reached or exceeded the maximum number of record resources in zone 'ci.azure.devcluster.openshift.com'. You have 10000 record resources of 10000 allowed.",
level=error msg=  "details": [
level=error msg=    {
level=error msg=      "code": "MaximumNumberOfRecordSetsReached",
level=error msg=      "message": "You have reached or exceeded the maximum number of record resources in zone 'ci.azure.devcluster.openshift.com'. You have 10000 record resources of 10000 allowed."
level=error msg=    }
level=error msg=  ]
level=error msg=}
level=error msg=--------------------------------------------------------------------------------
```
/retest

**Pull request merged**
