### PR TITLE
CONSOLE-3717: Dockerfile.rhel7: Drop explicit runlevels from some CRD manifests

### PR DESCRIPTION
**Pull request by wking**
It's unclear what the motivation was for their existing runlevels, with the API filenames landing without much context:

```console
openshift/api $ git --no-pager log --oneline operator/v1/0000_70_console-operator.crd.yaml | tail -n1
862dd2fe4 Add console-operator CRD and generate from types
openshift/api $ git --no-pager log -1 --format='%h %B' --stat=80 862dd2fe4
862dd2fe4 Add console-operator CRD and generate from types
    
 operator/v1/0000_70_console-operator.crd.yaml | 195 ++++++++++++++++++++++++++
 1 file changed, 195 insertions(+)
openshift/api $ git --no-pager log --oneline helm/*.crd.yaml | tail -n1
a4be43c2b Added ability to configure Helm chart repository accessible within cluster
openshift/api $ git --no-pager log -1 --format='%h %B' --stat=80 a4be43c2b
a4be43c2b Added ability to configure Helm chart repository accessible within cluster
    
* Introduced `HelmChartRepository` top-level CR modelled according to chartrepo.Entry
  from https://github.com/helm/helm/blob/master/pkg/repo/chartrepo.go#L42
* The corresponding enchancement: openshift/enhancements/pull/175
    
 Makefile                                           |   3 +-
 hack/update-deepcopy.sh                            |   2 +-
 hack/verify-crds.sh                                |   1 +
 .../0000_10-helm-chart-repository.crd.yaml         | 138 +++++++++++++++++++
 helm/v1alpha1/doc.go                               |   8 ++
 helm/v1alpha1/register.go                          |  38 ++++++
 helm/v1alpha1/types_helm.go                        | 108 +++++++++++++++
 helm/v1alpha1/zz_generated.deepcopy.go             | 152 +++++++++++++++++++++
 8 files changed, 448 insertions(+), 2 deletions(-)
openshift/api $ git --no-pager log --oneline helm/v1beta1/0000_10-project-helm-chart-repository.crd.yaml | tail -n1
8fe639fe2 helm: add a new namespaced CRD for helm
openshift/api $ git --no-pager log -1 --format='%h %B' --stat=80 8fe639fe2
8fe639fe2 helm: add a new namespaced CRD for helm
    
As part of the process to support namespace-scoped Helm repositories for
non-admin users, this PR adds a new namespace-scoped CRD definition
named `projecthelmchartrepositories.helm.openshift.io`.
    
Closes: https://issues.redhat.com/browse/HELM-258
Signed-off-by: Allen Bai <abai@redhat.com>
    
 .../0000_10-project-helm-chart-repository.crd.yaml | 130 +++++++++++++++++++++
 helm/v1beta1/register.go                           |   2 +
 ...ypes_helm.go => types_helm_chart_repository.go} |   0
 .../v1beta1/types_project_helm_chart_repository.go |  92 +++++++++++++++
 helm/v1beta1/zz_generated.deepcopy.go              | 119 +++++++++++++++++++
 5 files changed, 343 insertions(+)
```

Removing the explicit runlevels will allow these resources to go in with the other console resources in the default runlevel 50 ([docs][1], [implementation][2].

Significantly, the outgoing `0000_70_console-operator.crd.yaml` hadn't matched [the `0000_<runlevel>_<dash-separated-component>_<manifest_filename>` template][1], and by sorting lexically between other level-70 manifests:

```console
$ oc adm release extract --to manifests quay.io/openshift-release-dev/ocp-release:4.14.0-ec.4-x86_64
$ ls manifests | grep -1 0000_70_console-operator.crd.yaml
0000_70_cluster-network-operator_05_clusteroperator.yaml
0000_70_console-operator.crd.yaml
0000_70_dns-operator_00-cluster-role.yaml
```

it had been pushing the network and DNS manifests together into one large task-node.  With this change removing the unparsable attempt at a runlevel, the network and DNS manifests will be able to apply on updates via two parallel task-nodes.

[1]: https://github.com/openshift/enhancements/blob/cafeb5c3cba7f8c9e261b2aabffa92e34dd76be6/dev-guide/cluster-version-operator/dev/operators.md#what-is-the-order-that-resources-get-createdupdated-in
[2]: https://github.com/openshift/oc/blob/13225e00caf1ad2d3603e1d1cc8651833f2effcb/pkg/cli/admin/release/new.go#L1412-L1416

### CODE REVIEW

**Comment by wking** [comment]
Confirming the improved parallelization using [the update presubmit][1] and [CVO tooling][2], here's before:

```console
$ mkdir /tmp/initial
$ oc image extract registry.build03.ci.openshift.org/ci-op-y4s601c7/release:initial[-1] --path /:/tmp/initial
$ mkdir /tmp/initial/manifests
$ ./cluster-version-util task-graph /tmp/initial | dot -Tsvg >initial.svg
```

image

and after:

```console
$ mkdir /tmp/latest
$ oc image extract registry.build03.ci.openshift.org/ci-op-y4s601c7/release:latest[-1] --path /:/tmp/latest
$ mkdir /tmp/latest/manifests
$ ./cluster-version-util task-graph /tmp/latest | dot -Tsvg >lastest.svg
```

image

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console-operator/782/pull-ci-openshift-console-operator-master-e2e-azure-ovn-upgrade/1686455242079604736
[2]: https://github.com/openshift/cluster-version-operator/tree/9c0a4acf1afd6bd282ab451d2ebcd68c6dbc37f1/hack/cluster-version-util

**Comment by wking** [comment]
And in [the update CI run][1]'s CVO logs, Loki turns up:

```
...
I0801 20:53:06.977450       1 sync_worker.go:966] Precreated resource clusteroperator "dns" (713 of 858)   #<-- first dns precreation entry after update initiation
...
I0801 20:53:06.977815       1 sync_worker.go:966] Precreated resource clusteroperator "network" (703 of 858)   #<-- first network precreation entry after update initiation
...
I0801 20:55:25.358040       1 sync_worker.go:238] The sync worker already has a pending notification, so no need to inform about: Cluster operator dns changed versions[name="operator"] from "4.14.0-0.ci.test-2023-08-01-191417-ci-op-y4s601c7-initial" to "4.14.0-0.ci.test-2023-08-01-192002-ci-op-y4s601c7-latest"
...
I0801 21:07:30.493778       1 sync_worker.go:236] Notify the sync worker: Cluster operator network changed versions[name="operator"] from "4.14.0-0.ci.test-2023-08-01-191417-ci-op-y4s601c7-initial" to "4.14.0-0.ci.test-2023-08-01-192002-ci-op-y4s601c7-latest"
...
```

which shows we are saving the DNS operator's 2m20s (in that run) with this parallelization.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console-operator/782/pull-ci-openshift-console-operator-master-e2e-azure-ovn-upgrade/1686455242079604736

**Comment by wking** [comment]
[Build cluster hiccup][1]:

/test e2e-azure-ovn-upgrade

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console-operator/782/pull-ci-openshift-console-operator-master-e2e-azure-ovn-upgrade/1686503706402492416

**Comment by wking** [comment]
openshift/api#1544 merged, so I've rerolled this to pick that up with aba6cdc39 -> 833288fc5.  Also dropping the WIP:

/retitle CONSOLE-3717: Dockerfile.rhel7: Drop explicit runlevels from some CRD manifests

**Comment by wking** [comment]
[Three][1] [failed][2] [runs][3], but after poking around a bit, I'm not finding a clear connection to my changes.

/retest-required

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console-operator/782/pull-ci-openshift-console-operator-master-e2e-aws-console/1707099593948270592
[2]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console-operator/782/pull-ci-openshift-console-operator-master-e2e-aws-ovn-single-node/1707099594128625664
[3]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console-operator/782/pull-ci-openshift-console-operator-master-e2e-azure-ovn-upgrade/1707099594204123136

**Comment by wking** [comment]
Rebased around #796 with b2c48fe5b -> 58aacd844.

**Comment by jhadvig** [comment]
```
* 2023-10-12T12:06:45Z 1x kubelet: Pulling image "image-registry.openshift-image-registry.svc:5000/ci-op-q5qv5mjd/stable@sha256:a89f751b7891e2541752ccdc58e0939a19fe019bfabefdc49695efbe3bcd47c2"
Link to step on registry info site: https://steps.ci.openshift.org/reference/ipi-install-rbac
Link to job on registry info site: https://steps.ci.openshift.org/job?org=openshift&repo=console-operator&branch=master&test=e2e-aws-console, "e2e-aws-console" post steps failed: "e2e-aws-console" pod "e2e-aws-console-ipi-deprovision-deprovision" failed: could not watch pod: the pod ci-op-q5qv5mjd/e2e-aws-console-ipi-deprovision-deprovision failed after 19s (failed containers: test): ContainerFailed one or more containers exited
````

@wking does this error looks valid to you ?

**Comment by wking** [comment]
[Build cluster struggling][1], not our pull:

/retest-required

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console-operator/782/pull-ci-openshift-console-operator-master-e2e-aws-console/1712471110198497280

**Comment by jhadvig** [comment]
manually adding labels since the PR is updating the renamed manifests from the API repo.

**Pull request merged**
