### PR TITLE
PD-1365: Add quickstart - Get started with multicluster engine

### PR DESCRIPTION
**Pull request by jschuler**
cc @matthewcarleton

### CODE REVIEW

**Comment by jhadvig** [comment]
@jschuler could you please add a story to the PR? Thanks

**Comment by janwright73** [comment]
@jhadvig. Joachim is out on PTO this week. The corresponding UX story for this PR is: https://issues.redhat.com/browse/PD-1365.  Is this sufficient for the PR review?

**Comment by matthewcarleton** [comment]
more specifically there is a sub task here with a design doc
https://issues.redhat.com/browse/PD-1386

**Review by jhadvig — APPROVED** [review]
The changes are looking good 👍 
/lgtm
/approve

But not realle sure who should be signing all the approvals (Docs, PX, QE). @janwright73 could you please assist here. Thanks

**Comment by spadgett** [comment]
/label qe-approved
/label docs-approved

/assign @RickJWagner 
for px approval

**Pull request merged**
