### PR TITLE
Move the consoleoperator controller to lib-go controller factory

### PR DESCRIPTION
**Pull request by stlaz**
This PR moves the console operator controller to the newer library-go controller factory and removes the dependencies on the old controller framework.

It also wires context correctly.

/assign @jhadvig

### CODE REVIEW

**Comment by stlaz** [comment]
/retest
let's see if the issue is reproducible

**Comment by stlaz** [comment]
/retest
irrelevant

**Comment by stlaz** [comment]
/retest
irrelevant

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
