### PR TITLE
Bug 1971690: clidownloads: ARM 64 is supported

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Comment by spadgett** [comment]
@yselkowitz Do you mind opening a BZ to track?

**Review by jhadvig — APPROVED** [review]
/lgtm

**Comment by yselkowitz** [comment]
I don't mind, but this is intended for 4.9, and (last I checked) RHBZ isn't configured for 4.9 bugs yet.

**Comment by yselkowitz** [comment]
Can we drop the hold now?
/bugzilla refresh
/retest

**Pull request merged**
