### PR TITLE
Bug 1707478: Reorder manifests to ensure ClusterOperator is last

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Fix 1707478

ClusterOperator manifests should be last, or at least late enough to ensure that the operator will update it successfully.
- `/manifests/08-config-public.yaml` bumped to `/manifests/05-config-public.yaml` with our other configmap.  The only prerequisite for this configmap is the existence of the namespace `openshift-config-managed`, which we do not control here anyway.
- Bumped `downloads` related manifests from `08` and `09` to `07`, to match the operator.  This is arbirary, but simply ensures the ClusterOperator manifest is the final manifest (and the only one at `09`).

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1707478

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
PR opened in response to an error:

```
level=fatal msg=“failed to initialize the cluster: Working towards 0.0.1-2019-05-06-174943: 99% complete, waiting on console: timed out waiting for the condition”
```
Visible with [this query](https://ci-search-ci-search-next.svc.ci.openshift.org/chart?search=failed%20to%20initialize%20the%20cluster:%20.*console)

Related to [this failed CI run](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/operator-framework_operator-lifecycle-manager/816/pull-ci-operator-framework-operator-lifecycle-manager-master-e2e-aws-olm/1837).

In response to conversation in slack.

**Comment by spadgett** [comment]
> auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://integrated-oauth-server-openshift-authentication.apps.ci-op-rjrn57xz-ab436.origin-ci-int-aws.dev.rhcloud.com/oauth/token failed: Head https://integrated-oauth-server-openshift-authentication.apps.ci-op-rjrn57xz-ab436.origin-ci-int-aws.dev.rhcloud.com: dial tcp: lookup integrated-oauth-server-openshift-authentication.apps.ci-op-rjrn57xz-ab436.origin-ci-int-aws.dev.rhcloud.com on 172.30.0.10:53: no such host

/retest

**Comment by spadgett** [comment]
OAuth server wasn't ready, which blocked console rollout. (We should stop blocking on auth, but too late to make that change in 4.1.)

**Comment by bparees** [comment]
> OAuth server wasn't ready, which blocked console rollout. (We should stop blocking on auth, but too late to make that change in 4.1.)

is that a bug against oauth(why wasn't it ready)?

And does console retry when oauth isn't ready?

**Comment by enj** [comment]
Networking related:

```
                    {
                        "lastTransitionTime": "2019-05-06T20:11:52Z",
                        "message": "Degraded: error checking current version: unable to check route health: failed to GET route: dial tcp: lookup integrated-oauth-server-openshift-authentication.apps.ci-op-rjrn57xz-ab436.origin-ci-int-aws.dev.rhcloud.com on 172.30.0.10:53: no such host",
                        "reason": "DegradedOperatorSyncLoopError",
                        "status": "True",
                        "type": "Degraded"
                    },
```

**Comment by spadgett** [comment]
> And does console retry when oauth isn't ready?

Yes, we keep trying until we can connect to the OAuth server.

**Comment by spadgett** [comment]
```
2019/05/06 19:51:45 Running pod e2e-aws-upgrade
2019/05/06 20:17:33 Container setup in pod e2e-aws-upgrade completed successfully
{"component":"entrypoint","level":"error","msg":"Process did not finish before 2h0m0s timeout","time":"2019-05-06T21:49:33Z"}
2019/05/06 21:49:34 error: Process interrupted with signal interrupt, exiting in 10s ...
2019/05/06 21:49:34 cleanup: Deleting release pod release-latest
2019/05/06 21:49:34 cleanup: Deleting release pod release-initial
2019/05/06 21:49:34 cleanup: Deleting template e2e-aws-upgrade
rpc error: code = 2 desc = containerd: container not found
{"component":"entrypoint","level":"error","msg":"Process gracefully exited before 15s grace period","time":"2019-05-06T21:49:44Z"}
```

/retest

**Comment by spadgett** [comment]
```
info: Loading sha256:2818ae6b66af928d478db15ac4d1a5a91f85b91d401a09bbb539d19662c53eda service-ca-operator
info: Included 86 images from 30 input operators into the release
error: unable to upload the new image manifest: received unexpected HTTP status: 504 Gateway Time-out
```

/retest

**Comment by bparees** [comment]
@enj @spadgett at this point in the release i think every one of those PR job failures should be opened as a bug (the 504 gateway error is a bug against test infra though, it's not a 4.1 bug).

**Comment by spadgett** [comment]
@bparees Opened https://bugzilla.redhat.com/show_bug.cgi?id=1707510 for the first failure.

**Pull request merged**
