### PR TITLE
[WIP] Devconsole crd

### PR DESCRIPTION
**Pull request by DhritiShikhar**
To enable developer perspective in openshift

### CODE REVIEW

**Comment by spadgett** [comment]
> To enable developer perspective in openshift

This should be a flag on the existing console config object: https://github.com/openshift/api/blob/master/config/v1/types_console.go

/hold

**Comment by sbose78** [comment]
Sam , using the existing console-config object might make it unusable in OSDs.
I've outlined options in https://docs.google.com/document/d/1B_ScB3uMEM1ziAC_NE5rEMLo3IK8Ug3BGAZBdENjPhk

**Comment by benjaminapetersen** [comment]
It is also not clear to me why we need an additional config object.

**Comment by spadgett** [comment]
> Sam , using the existing console-config object might make it unusable in OSDs.

This will be a problem for every console config flag, not just dev console. Creating a separate CRD for each feature doesn't scale and is inconsistent with how other components handle configuration. We need to address console configuration generally in OSD.

cc @bparees

**Comment by bparees** [comment]
> This will be a problem for every console config flag, not just dev console. Creating a separate CRD for each feature doesn't scale and is inconsistent with how other components handle configuration. We need to address console configuration generally in OSD.

+1.  We need to talk to the OSD team and understand the concerns/risks if a dedicated-cluster-admin is able to edit the console config resource.  Or what other mechanism OSD might offer to allow the customer to control this configuration.

**Pull request closed without merging**
