### PR TITLE
Bug 1767926: Bump vendor

### PR DESCRIPTION
**Pull request by benjaminapetersen**
- pickup [openshift/api #507](https://github.com/openshift/api/pull/507) for consoleyamlsample targetResource bug fix
  - bug #1767926

/assign @spadgett @jhadvig

### CODE REVIEW

**Comment by jhadvig** [comment]
s3 flake
/retest

**Comment by jhadvig** [comment]
```

**Comment by spadgett** [comment]
@christianvogt @andrewballantyne FYI, this fixes the `targetResource` YAML sample bug. We'll track the `snippet` change separately.

**Comment by benjaminapetersen** [comment]
/retest

Console test flake?
`StaleElementReferenceError: stale element reference: element is not attached to the page document`

**Comment by benjaminapetersen** [comment]
/retest 

`level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"`

**Pull request merged**
