### PR TITLE
OCPBUGS-15827: Revert #831 and fix cluster proxy annotation on console conversion webhook deployment

### PR DESCRIPTION
**Pull request by TheRealJon**
Revert #831 to re-apply fix for OCPBUGS-15827. 
Fix conversion webhook deployment proxy annotation in IBM cloud management manifest.

### CODE REVIEW

**Comment by TheRealJon** [comment]
/payload-job periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
