### PR TITLE
[release-4.11] OCPBUGS-5499: Add host inventory quickstart

### PR DESCRIPTION
**Pull request by chenz4027**

### CODE REVIEW

**Comment by chenz4027** [comment]
Removing annotation worked!  Thanks @jhadvig 👍 
image

**Comment by yanpzhan** [comment]
Checked on cluster launched against the pr, the host inventory quickstart is shown on page now.
/lable qe-approved

**Comment by jhadvig** [comment]
@yanpzhan since we are backporting bug here we need to add `cherry-pick-approved` label, not `qe-appoved`.
Since the testing was successful, adding it manually

**Pull request merged**
