### PR TITLE
ODC-7418: Add Janus IDP and RHDH Quick starts

### PR DESCRIPTION
**Pull request by jerolimov**
**Implements:**
https://issues.redhat.com/browse/ODC-7418

This PR adds four new Quick Starts:

1. Install Janus IDP with a Helm Chart ([QuickStart YAML on GitHub](https://github.com/jerolimov/console-operator/blob/janus-rhdh-quickstarts/quickstarts/janus-idp-installation-via-helm.yaml))
2. Install Janus IDP with an Operator ([QuickStart YAML on GitHub](https://github.com/jerolimov/console-operator/blob/janus-rhdh-quickstarts/quickstarts/janus-idp-installation-via-operator.yaml))
3. Install Red Hat Developer Hub (RHDH) with a Helm Chart ([QuickStart YAML on GitHub](https://github.com/jerolimov/console-operator/blob/janus-rhdh-quickstarts/quickstarts/rhdh-installation-via-helm.yaml))
4. Install Red Hat Developer Hub (RHDH) with an Operator ([QuickStart YAML on GitHub](https://github.com/jerolimov/console-operator/blob/janus-rhdh-quickstarts/quickstarts/rhdh-installation-via-operator.yaml))

To install the Quickstarts directly from this PR (my branch) you can also run this `kubectl`/`oc` commands to apply them to your cluster:

```bash
kubectl apply -f https://github.com/jerolimov/console-operator/raw/janus-rhdh-quickstarts/quickstarts/janus-idp-installation-via-helm.yaml
kubectl apply -f https://github.com/jerolimov/console-operator/raw/janus-rhdh-quickstarts/quickstarts/janus-idp-installation-via-operator.yaml
kubectl apply -f https://github.com/jerolimov/console-operator/raw/janus-rhdh-quickstarts/quickstarts/rhdh-installation-via-helm.yaml
kubectl apply -f https://github.com/jerolimov/console-operator/raw/janus-rhdh-quickstarts/quickstarts/rhdh-installation-via-operator.yaml
```

### Preview

Please review the full Quick starts via the YAMLs above. These screenshots don't contain all the pages!

image

image

image

/cc @yuvalgalanti @invincibleJai @debsmita1 @divyansh42

### CODE REVIEW

**Review by vikram-raj — COMMENTED** [review]
Verified it with the cluster bot and able to see all four quick starts from this PR. 


https://github.com/openshift/console-operator/assets/2561818/58660eb5-84b8-487c-8993-3fa9d6f27122

/lgtm

**Comment by sanketpathak** [comment]
As it's been verified using cluster-bot
/label qe-approved

**Comment by jerolimov** [comment]
Not critical, but there is no risk to add new quick starts. 🤞 

/label acknowledge-critical-fixes-only
/label px-approved
/label docs-approved

**Pull request merged**
