### PR TITLE
Bump openshift/api to get customize catalog categories changes

### PR DESCRIPTION
**Pull request by jerolimov**
Issue: https://issues.redhat.com/browse/ODC-5020

Update openshift/api in vendor folder to get the latest update from https://github.com/openshift/api/pull/763

(Does not include a go.mod/sum update yet, will update this PR when the api PR is merged.)

### CODE REVIEW

**Comment by jerolimov** [comment]
> extensions_crud_test.go:16: Console.operator.openshift.io "cluster" is invalid: spec.customization.developerCatalog.categories: Invalid value: "null": spec.customization.developerCatalog.categories in body must be of type array: "null"

Added omitempty to customization.developerCatalog and customization.developerCatalog.categories

**Comment by jhadvig** [comment]
Added couple of [comments to the API PR](https://github.com/openshift/api/pull/763#pullrequestreview-541784697)

**Comment by jerolimov** [comment]
@jhadvig I have accepted all suggestions and rebased this PR.

**Pull request merged**
