### PR TITLE
Bug 2001523: Set Available condition to False when console-operator in Removed state

### PR DESCRIPTION
**Pull request by jhadvig**
We should report `Available` condition set to `False` when operator is in `Removed` state.

/assign @spadgett

### CODE REVIEW

**Comment by spadgett** [comment]
@wking Can you confirm this is the right behavior?

We should confirm setting "Available: false" doesn't block upgrades when console is removed.

**Comment by wking** [comment]
> We should confirm setting "Available: false" doesn't block upgrades when console is removed.

Setting `Available: False` will absolutely [block updates][1], and fire off `critical` alerts, and all sorts of bad things.  Please don't do that ;).  openshift/api#1000 is my in-flight effort to clarify these condition semantics.  Applied to this case, if the user asked you to remove your operand, and you have successfully removed it, then you are `Available: True`, meaning "everything my component is configured to be doing, it's successfully doing".

[1]: https://github.com/openshift/enhancements/blob/98f33c569d9d5f86f91b12cfa8a1ce86ece72066/dev-guide/cluster-version-operator/user/reconciliation.md#ClusterOperator

**Comment by spadgett** [comment]
> Setting `Available: False` will absolutely [block updates](https://github.com/openshift/enhancements/blob/98f33c569d9d5f86f91b12cfa8a1ce86ece72066/dev-guide/cluster-version-operator/user/reconciliation.md#ClusterOperator), and fire off `critical` alerts, and all sorts of bad things. Please don't do that ;). [openshift/api#1000](https://github.com/openshift/api/pull/1000) is my in-flight effort to clarify these condition semantics. Applied to this case, if the user asked you to remove your operand, and you have successfully removed it, then you are `Available: True`, meaning "everything my component is configured to be doing, it's successfully doing".

Thanks, @wking. Closing the PR.

/close

**Pull request closed without merging**
