### PR TITLE
Move to go mods, use openshift/build-machinery-go for building

### PR DESCRIPTION
**Pull request by stlaz**

### CODE REVIEW

**Comment by stlaz** [comment]
You appear to be using go 1.12 for your builds is why all builds fail, I thought 1.13 was a requirement since kube 1.17 (or perhaps even earlier)

**Comment by stlaz** [comment]
depends on https://github.com/openshift/release/pull/8087

**Comment by benjaminapetersen** [comment]
/retest

openshift/release#8087 merged

**Comment by jhadvig** [comment]
```
=== RUN   TestEditManagedRoute
--- FAIL: TestEditManagedRoute (243.28s)
    managed_test.go:13: waiting for setup to reach settled state...
    util.go:72: patching TargetPort on the console Route
    util.go:79: polling for patched TargetPort on the console Route
    managed_test.go:17: waiting for cleanup to reach settled state...
    console-operator.go:369: waited 10 seconds to reach settled state...
    console-operator.go:369: waited 30 seconds to reach settled state...
    console-operator.go:369: waited 60 seconds to reach settled state...
    console-operator.go:369: waited 90 seconds to reach settled state...
    console-operator.go:369: waited 120 seconds to reach settled state...
    managed_test.go:17: operator has not reached settled state in 4m0s attempts due to [RouteHealthDegraded] - timed out waiting for the condition
```

**Pull request merged**
