### PR TITLE
OCPBUGS-5893: Back port on-premise host inventory quick start to OCP 4.10

### PR DESCRIPTION
**Pull request by chenz4027**
https://issues.redhat.com/browse/OCPBUGS-5893

### CODE REVIEW

**Comment by yanpzhan** [comment]
Checked on cluster launched against the pr, the host inventory quickstart and multicluster engine quickstart are shown correctly.
/label qe-approved
/label cherry-pick-approved

**Review by jhadvig — APPROVED** [review]
/lgtm

**Pull request merged**
