### PR TITLE
Call StandardSetup func in unmanaged e2e tests

### PR DESCRIPTION
**Pull request by jhadvig**
/assign @benjaminapetersen

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
/retest

Console test error

**Comment by benjaminapetersen** [comment]
/retest

Jasmine timeout

**Comment by benjaminapetersen** [comment]
/hold

Rebase needed

**Comment by benjaminapetersen** [comment]
Probably related to disable

**Comment by jhadvig** [comment]
PR rebased, @benjaminapetersen PTAL

**Comment by jhadvig** [comment]
Closing in favour of https://github.com/openshift/console-operator/pull/338

**Pull request closed without merging**
