### PR TITLE
OCPBUGS-11298: Disable multicluster tech preview

### PR DESCRIPTION
**Pull request by TheRealJon**

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Comment by stbenjam** [comment]
Hi folks, would you mind waiting for the results of the payload command to merge this? It looks like there's some successful presubmit upgrades, but I'm not sure 2 are enough (on the original payload failures, we were seeing 60-70% upgrade failure rate).  Are we sure all of the RBAC problems are resolved here?

https://github.com/openshift/console-operator/pull/749#issue-1659069279 asked for the payload command so we'd get a good signal this change doesn't break upgrades more:

```
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of to confirm upgrade succeed:

/payload 4.14 ci blocking
```

/hold
/payload 4.14 ci blocking

**Comment by TheRealJon** [comment]
@stbenjam Yes, apologies, I missed that comment. We will hold off on merging this until these jobs have passed. I removed all changes to the console-operator cluster role which should address the issue from the original PR.

**Comment by stbenjam** [comment]
Upgrades looks clean, thank you 🙏🏻 

https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregator-periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-azure-sdn-upgrade/1645822227146346496
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregator-periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-ovn-upgrade/1645822236365426688

**Comment by TheRealJon** [comment]
/retest
Flakes in other components

**Pull request merged**
