### PR TITLE
Reorganize args to NewConsoleOperator func

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Reorganize args to NewConsoleOperator() to fit client/informer sets together.

This will make it easier to extract out components into separate controllers. 

/assign @jhadvig

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
/retest

`
level=fatal msg="failed to initialize the cluster: Cluster operator image-registry is still updating"
`

**Comment by jhadvig** [comment]
```

**Comment by benjaminapetersen** [comment]
/retest

`level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"
`

**Pull request merged**
