### PR TITLE
OCPBUGS-22681: Bump documentationBaseURL to 4.15

### PR DESCRIPTION
**Pull request by jhadvig**
/assign @TheRealJon

### CODE REVIEW

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Comment by yanpzhan** [comment]
Checked on cluster launched against the pr, baseurl is 4.15 now:
documentationBaseURL: https://access.redhat.com/documentation/en-us/openshift_container_platform/4.15/
/label qe-approved
/label cherry-pick-approved

**Pull request merged**
