### PR TITLE
Switching the URL of the default openshift helm repo.

### PR DESCRIPTION
**Pull request by dperaza4dustbit**
All OpenShift charts will come from the repo with OpenShift
certified charts. All the charts in the current repo will go
through the certification program https://charts.openshift.io

### CODE REVIEW

**Comment by dperaza4dustbit** [comment]
Please do not merge this yet, will let you know when certification program is GAd (schedule for may 18). Wanted to start socializing as the charts on this new repo will come gradually. It will not have the same charts as in https://redhat-developer.github.io/redhat-helm-charts at the beginning. Here is the link to the OpenShift Helm certification program: https://charts.openshift.io

**Comment by christianvogt** [comment]
/hold 
see https://github.com/openshift/console-operator/pull/545#issuecomment-840626512

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

lets remote `hold` once the certification program is GAd. Thanks!

**Comment by dperaza4dustbit** [comment]
Certification program if GA, I think we can move this PR forward now, thanks

**Pull request merged**
