### PR TITLE
CONSOLE-4055: Have GettingStartedBanner enabled by default

### PR DESCRIPTION
**Pull request by jhadvig**
Forgot to include this change in https://github.com/openshift/console-operator/pull/927

/assign @TheRealJon

### CODE REVIEW

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Comment by jhadvig** [comment]
QE Approver:
/assign @yapei
Docs Approver:
/assign @opayne1
PX Approver:
/assign @reestr

**Comment by yapei** [comment]
@XiyunZhao is working on PR verification and will report back

**Comment by XiyunZhao** [comment]
No issue was found on the pre-merge testing, the changes are working as expected on console-operator's config
/label qe-approved

**Pull request merged**
