### PR TITLE
Update oc clidownload cr to indicate that certain builds are unsupported

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Will be a backport to 4.4 & 4.3.z.

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
/retest

```
release "release-latest" failed: the pod ci-op-hdb6w97j/release-latest failed after 23s (failed containers: release): ContainerFailed one or more containers exited

Container release exited with code 1, reason Error
---
info: Using registry public hostname registry.svc.ci.openshift.org
Saved credentials for registry.svc.ci.openshift.org
info: Found 244 images in image stream
error: unable to read image registry.svc.ci.openshift.org/ci-op-hdb6w97j/stable@sha256:595142acf537b1b17b8e340c2de6b73364c79034401d58f5b09dfbd6b742e5c8: received unexpected HTTP status: 500 Internal Server Error
---
```

**Comment by yselkowitz** [comment]
@benjaminapetersen on what basis are you declaring the IBM architectures as unsupported when we are in the very process of officially enabling those architectures?

**Pull request merged**
