### PR TITLE
Bug 1748280: Pod CrashLoop cause by library-go + Bump

### PR DESCRIPTION
**Pull request by jhadvig**
/assign @benjaminapetersen 

The issue was traced down to the library-go where the sync is not couting with the `binaryData` field. It was fixed in https://github.com/openshift/library-go/pull/520
Bump is carrying the fix.

Tested the fix manually and its solving the issue.

### CODE REVIEW

**Comment by spadgett** [comment]
Looks like some files in vendor are failing gofmt. Can we exclude those directories?

**Comment by jhadvig** [comment]
@spadgett fixed the issue, needed to clean the cache. Should be fine now

**Comment by spadgett** [comment]
> The issue was traced down to the library-go where the sync is not couting with the `binaryData` field. It was fixed in [openshift/library-go#520](https://github.com/openshift/library-go/pull/520)

Nice job tracking this down!

**Pull request merged**
