### PR TITLE
Enable ci

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Some additions for enabling CI.

Fixes issue #11  
Fixes issue #4 
Fixes issue #2 

Related to release PR https://github.com/openshift/release/pull/1653

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
@spadgett @jwforres @enj anyone out there who can /lgtm me so I can see CI merge this and count it successful 😄

**Comment by jwforres** [comment]
/lgtm

woo!

**Pull request merged**
