### PR TITLE
CONSOLE-3912: Merge auth cert configmap deployment annotations into one

### PR DESCRIPTION
**Pull request by liouk**
This is a follow-up on #811/#839 (see [this](https://github.com/openshift/console-operator/pull/811#discussion_r1426816316) comment).

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Comment by liouk** [comment]
/retest
build03 cluster issues

**Comment by jhadvig** [comment]
Adding tags manually since we are just refactoring code.

**Pull request merged**
