### PR TITLE
CONSOLE-3438: Switch to using assets

### PR DESCRIPTION
**Pull request by raspbeep**
Switch from using generated bindata to assets eliminates the need to regenerate bindata whenever there are modifications to YAML files. Additionally, it addresses the issue of generating bindata on ARM and other architectures, making the bindata generation process obsolete.

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Comment by jhadvig** [comment]
QE Approver: 
/assign @yanpzhan
PX Approver:
/assign @RickJWagner
Docs Approver:
/assign @opayne1

**Comment by yanpzhan** [comment]
@raspbeep Hi, I have done regression test on console, if there are any special points need to be checked?

**Comment by jhadvig** [comment]
@yanpzhan thanks for testing, there is no special case for testing needed, since we are just changing way how the assets are being generated/read.

**Comment by yanpzhan** [comment]
Thanks, Jakub!
/label qe-approved

**Pull request merged**
