### PR TITLE
Bug 1883692: bump(api) to get LogLevel validation

### PR DESCRIPTION
**Pull request by sttts**
openshift/api#736 added restrictions for logLevel values. This PR vendors new openshift/api to get new CRDs.

### CODE REVIEW

**Comment by spadgett** [comment]
https://github.com/openshift/release/pull/12292#event-3820494628 has merged

/retest

**Comment by dmage** [comment]
@sttts https://github.com/openshift/console-operator/commit/d9926d7755805a832fba5728209788a447b50006 - this fixes the problem with sigs.k8s.io/structured-merge-diff/v3 and v4

**Comment by dmage** [comment]
/retitle Bug 1883692: bump(api) to get LogLevel validation

**Comment by jhadvig** [comment]
Closing due to merge of https://github.com/openshift/console-operator/pull/473

**Pull request closed without merging**
