### PR TITLE
CONSOLE-2757: Bump github.com/openshift/api 

### PR DESCRIPTION
**Pull request by jhadvig**
To pickup changes from https://github.com/openshift/api/pull/827

/assign @spadgett

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm
/hold for approvals
/assign @yapei @sferich888 @ahardin-rh 

@yapei This is needed for the single node story, but it only updates the openshift/api dependency. So for now we just need to check for regressions. Thank you!

**Comment by jhadvig** [comment]
Looks like flaky tests
/retest

**Comment by jhadvig** [comment]
Looks like flaky tests
/retest

**Comment by yapei** [comment]
QE did some regression testing and  no issues found.

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by sferich888** [comment]
As part of this work we also need to work within https://issues.redhat.com/browse/CONSOLE-2759 to provide enablement for the support / field teams.

**Comment by jhadvig** [comment]
@spadgett I've accidentally pushed into this this branch. Could you please re-tag.
Sorry & thanks :)

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
