### PR TITLE
OCPBUGS-457: TestEditUnmanagedPodDisruptionBudget flakes

### PR DESCRIPTION
**Pull request by jhadvig**
/assign @TheRealJon

### CODE REVIEW

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Comment by jerolimov** [comment]
This error `TestEditUnmanagedPodDisruptionBudget` happens currently in

> 41 runs, 85% failed, 23% of failures match = 20% impact
>
> from https://search.ci.openshift.org/?search=TestEditUnmanagedPodDisruptionBudget&maxAge=336h&context=1&type=bug%2Bjunit&name=pull-ci-openshift-console-operator-master-e2e-aws-operator&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

The 3 tests in this PR passes. Running this once again and removing the auto-hold as this has lgtm.

/retest e2e-aws-operator
/unhold

**Pull request merged**
