### PR TITLE
CONSOLE-3397: Remove managed cluster API server data from managed clu…

### PR DESCRIPTION
**Pull request by TheRealJon**
…ster configs

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Comment by jhadvig** [comment]
```
--- FAIL: TestUnmanaged (37.21s)
```

/retest

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Comment by jhadvig** [comment]
QE Approver: 
/assign @yapei
Docs Approver:
 /assign @opayne1
PX Approver:
 /assign @RickJWagner

**Comment by jhadvig** [comment]
@TheRealJon once this PR is merged we should open a console PR that will update serverconfig types accordingly.

**Comment by TheRealJon** [comment]
/hold

QE feedback

**Pull request closed without merging**
