### PR TITLE
Bug 2093852: InfrastructureTopology must be driving console affinity rule creation

### PR DESCRIPTION
**Pull request by michael-topchiev**
This PR fixes bug described in the issue https://github.com/openshift/console-operator/issues/656

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Comment by jhadvig** [comment]
gcp test failure:
```
8 passing (2m)
  1 failing
  1) Cluster dashboard
       Details Card
         has all fields populated:
      AssertionError: Timed out retrying after 30000ms: Not enough elements found. Found '5', expected '6'.
      + expected - actual
      -5
      +6
```

**Comment by michael-topchiev** [comment]
@jhadvig any code changes required to make e2e-gcp test pass? Pleased let us know what is needed for this PR to be released?

**Pull request merged**
