### PR TITLE
[release-4.16] OCPBUGS-33788: Tolerate the absence of ingress capability on HyperShift clusters

### PR DESCRIPTION
**Pull request by alebedev87**
Backport of https://github.com/openshift/console-operator/pull/886.

### CODE REVIEW

**Comment by alebedev87** [comment]
`[Add cluster wide trusted CA bundle to operator](https://github.com/openshift/console-operator/pull/910/commits/6f483ab12f86d02289231bb9bc0ee818236ddb54)` commit added.

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
