### PR TITLE
ODC-7339: Follow up ticket for ODC-7292

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
Updated Cryostat quick start for PR comment - https://github.com/openshift/console-operator/pull/770#pullrequestreview-1501727662

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Based on https://github.com/openshift/console-operator/pull/770#pullrequestreview-1501727662

/lgtm
/approved

**Comment by lokanandaprabhu** [comment]
Propage labels from the epic:

/label docs-approved
/label px-approved

**Comment by jerolimov** [comment]
Adding QE approved since this change only adds new content. @sanketpathak FYI. Please let me/us know if you have any issue with this.

/label qe-approved

**Pull request merged**
