### PR TITLE
OCPBUGS-11164: Disable multicluster tech preview

### PR DESCRIPTION
**Pull request by TheRealJon**

### CODE REVIEW

**Comment by TheRealJon** [comment]
/hold

Waiting on input as to whether we should also remove roles and rolebindings from the manifests.

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by TheRealJon** [comment]
@spadgett I've updated to remove multicluster roles/bindings from the manifests and delete the code from starter.go rather than comment it out. PTAL when you get a chance!

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
