### PR TITLE
OCPBUGS-20466: Tighten console operator permissions for cluster operators

### PR DESCRIPTION
**Pull request by TheRealJon**

### CODE REVIEW

**Comment by TheRealJon** [comment]
/hold

Not sure why restricting permissions on clusteroperators is causing problems with the ouauth controller

**Review by jhadvig — COMMENTED** [review]
Looks like operator is unable to list/watch the clusteroperators resource, but I dont understand why??
```
2024-03-13T15:41:16.899136935Z W0313 15:41:16.899084       1 reflector.go:539] github.com/openshift/client-go/config/informers/externalversions/factory.go:125: failed to list *v1.ClusterOperator: clusteroperators.config.openshift.io is forbidden: User "system:serviceaccount:openshift-console-operator:console-operator" cannot list resource "clusteroperators" in API group "config.openshift.io" at the cluster scope
2024-03-13T15:41:16.899136935Z E0313 15:41:16.899115       1 reflector.go:147] github.com/openshift/client-go/config/informers/externalversions/factory.go:125: Failed to watch *v1.ClusterOperator: failed to list *v1.ClusterOperator: clusteroperators.config.openshift.io is forbidden: User "system:serviceaccount:openshift-console-operator:console-operator" cannot list resource "clusteroperators" in API group "config.openshift.io" at the cluster scope
```

**Comment by TheRealJon** [comment]
> Looks like operator is unable to list/watch the clusteroperators resource, but I dont understand why??
> 
> ```
> 2024-03-13T15:41:16.899136935Z W0313 15:41:16.899084       1 reflector.go:539] github.com/openshift/client-go/config/informers/externalversions/factory.go:125: failed to list *v1.ClusterOperator: clusteroperators.config.openshift.io is forbidden: User "system:serviceaccount:openshift-console-operator:console-operator" cannot list resource "clusteroperators" in API group "config.openshift.io" at the cluster scope
> 2024-03-13T15:41:16.899136935Z E0313 15:41:16.899115       1 reflector.go:147] github.com/openshift/client-go/config/informers/externalversions/factory.go:125: Failed to watch *v1.ClusterOperator: failed to list *v1.ClusterOperator: clusteroperators.config.openshift.io is forbidden: User "system:serviceaccount:openshift-console-operator:console-operator" cannot list resource "clusteroperators" in API group "config.openshift.io" at the cluster scope
> ```
> 
> Why we need to list clusteroperators?

I think I figured this out. I don't think we can use 'resourceNames' with 'list' verb, but we do need to list clusteroperators in order for the informers to work. To fix this, I split the rule for clusteropertors into two. One rule for read permissions on all cluster operators, one for write permission just on the console cluster operator.

**Comment by TheRealJon** [comment]
/retest

etcd issue

**Pull request merged**
