### PR TITLE
Fast forward multi cluster feature branch

### PR DESCRIPTION
**Pull request by TheRealJon**

### CODE REVIEW

**Comment by florkbr** [comment]
@TheRealJon the fix for the failing verify job on master was merged in on https://github.com/openshift/console-operator/pull/615. Did you want to include that PR in this fast forward? Or should I open a PR with the fix I had opened in https://github.com/openshift/console-operator/pull/619 against `master-multi-cluster-feature`?

**Comment by TheRealJon** [comment]
@florkbr I'm going to close this PR. I think there is a legit test failure happening and rather than try to fix it here, I'm going to address the issue in #612

**Pull request closed without merging**
