### PR TITLE
Rename Dockerfile.rhel7 -> Dockerfile.rhel

### PR DESCRIPTION
**Pull request by benjaminapetersen**
@adammhaile per conversation.
@spadgett fyi

coordination:
- [ ] Update https://github.com/openshift/ocp-build-data/blob/openshift-4.0/images/openshift-enterprise-console-operator.yml#L3 at EXACTLY the same time.  If not, builds will break.

### CODE REVIEW

**Comment by adammhaile** [comment]
This will need an update to ocp-build-data

**Comment by spadgett** [comment]
@benjaminapetersen @adammhaile I believe we can switch to a single Dockerfile when #180 is done

**Comment by benjaminapetersen** [comment]
This is no longer needed, we will not be building 2 images.
Semi-related to #180

**Pull request closed without merging**
