### PR TITLE
[release-4.17] OCPBUGS-36213: Vendor proper commit

### PR DESCRIPTION
**Pull request by jhadvig**
Updating the vendor API version, using the merge commit.
/assign @TheRealJon

### CODE REVIEW

**Comment by yanpzhan** [comment]
@jhadvig  could you help to rebase the pr? Thanks!

**Comment by yanpzhan** [comment]
Checked on cluster launched against the pr. No consoleplugin crd has spec.conversion.strategy is "None".
/label qe-approved
/label cherry-pick-approved

**Comment by jhadvig** [comment]
Overriding the OVN upgrade test due to constant flakes and since this fix needs to get into last RC build for 4.17
/override ci/prow/e2e-azure-ovn-upgrade

**Pull request merged**
