### PR TITLE
OCPBUGS-33787: deps: bump openshift/api

### PR DESCRIPTION
**Pull request by alebedev87**
- Remove all code associated with discontinued v1alpha1 API (webhook)
- Remove webhook manifests
- Update client-go to eliminate v1alpha1 dependencies
- Update dependencies: k8s.io/component-base, k8s.io/apiserver
- Use `ConditionApplyConfiguration` for the auth status
- Vendor generated CRDs

Related PR: https://github.com/openshift/console-operator/pull/886.

### CODE REVIEW

**Comment by alebedev87** [comment]
Webhook manifests removed

**Comment by alebedev87** [comment]
Rebased from `master`.

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Comment by alebedev87** [comment]
`e2e-aws-console` failures are related to https://github.com/openshift/console/pull/13887.

**Comment by alebedev87** [comment]
Cluster installation problem:
```
level=fatal msg=failed to fetch Cluster Infrastructure Variables: failed to fetch dependency of "Cluster Infrastructure Variables": failed to generate asset "Platform Provisioning Check": baseDomain: Invalid value: "origin-ci-int-aws.dev.rhcloud.com": the zone already has record sets for the domain of the cluster: [api.ci-op-t41xx8zp-be832.origin-ci-int-aws.dev.rhcloud.com. (A)]
209
Installer exit with code 1
```

**Comment by alebedev87** [comment]
`e2e-aws-console` is unstable, see [the test PR with empty commit](https://github.com/openshift/console-operator/pull/909) which failed 4 times in a row.

**Comment by jhadvig** [comment]
Overriding since our console integration tests are flaking pretty heavily
/override ci/prow/e2e-aws-console

**Pull request merged**
