### PR TITLE
CONSOLE-3069: Handle new v1 ConsolePlugin api in the operator

### PR DESCRIPTION
**Pull request by jhadvig**
This is an additional PR for https://issues.redhat.com/browse/CONSOLE-3069 to swap api towards the new `v1` version of ConsolePlugin CRD.
Updated packages and also tests.

/assign @TheRealJon

### CODE REVIEW

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Comment by jhadvig** [comment]
QE Approver:
 /assign [@yapei](https://github.com/yapei)

**Comment by yapei** [comment]
tested the PR with all steps in OCP-54170, no regressions
/label qe-approved

**Comment by jhadvig** [comment]
Adding docs and px labels manually since this PR is part of the same story.

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Pull request merged**
