### PR TITLE
[release-4.10] OCPBUGS-14845: Distinguish between route conditions and remove the old ones

### PR DESCRIPTION
**Pull request by palonsoro**
Backport of:

- https://github.com/openshift/console-operator/pull/745

### CODE REVIEW

**Comment by palonsoro** [comment]
Not sure from where on Earth this thing says that the bug targets 4.11.z when I have set it already to 4.10.z. 

Retrying....

**Review by jhadvig — APPROVED** [review]
/approve

**Comment by yapei** [comment]
not sure why it keeps complaining JIRA is invalid, in fact the linked JIRA issue already has target version set to `4.10.z`

**Comment by palonsoro** [comment]
@yapei I have opened internal ticket about the same. It seems that the bot has some problem.

**Comment by yanpzhan** [comment]
Built an image against the pr for testing:
1. Launched a sno cluster with the built image, patch console operator with these conditions are True: "CustomRouteSyncDegraded",	"CustomRouteSyncProgressing","DefaultRouteSyncDegraded","DefaultRouteSyncProgressing", they will be recovered/removed at once. Upgrade the cluster to 4.11 nightly build, the upgrade completed successfully.
2. Launch a 4.9.59 sno cluster, patch console operator with these conditions are True: "CustomRouteSyncDegraded",	"CustomRouteSyncProgressing","DefaultRouteSyncDegraded","DefaultRouteSyncProgressing", the console operator is shown as degraded. Upgrade the cluster to the built image, the upgrade completed successfully.
The fix works well.
/label qe-approved
/label cherry-pick-approved

**Pull request merged**
