### PR TITLE
Public hostname should be the hostname, not URL

### PR DESCRIPTION
**Pull request by spadgett**
/assign @benjaminapetersen @enj

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
Will we want to change this back after https://github.com/openshift/api/pull/212

**Comment by spadgett** [comment]
> Will we want to change this back after [openshift/api#212](https://github.com/openshift/api/pull/212)

Yeah, but I am putting this fix in for now in case there's disagreement on the API or the API changes don't make it in.

**Pull request merged**
