### PR TITLE
Bug 1764316: 4.2 Backport of e2e test for /metrics

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Original PR: #299 

/cc @spadgett @jhadvig

### CODE REVIEW

**Comment by spadgett** [comment]
We'll need a bugzilla for both the original for 4.3 change and a clone for 4.2.z to be able to backport the test

**Comment by benjaminapetersen** [comment]
This state is fine, the `4.3` version is still open.

**Comment by benjaminapetersen** [comment]
Closing for now.  Too much noise. WIll reopen backports when the 4.3 fix is settled.

**Pull request closed without merging**
