### PR TITLE
Improvements to the Install Serverless Operator quick start

### PR DESCRIPTION
**Pull request by serenamarie125**
Addressing issues from UX : https://issues.redhat.com/browse/ODC-5470

@openshift/quickstart-ux-content  please review

Here is a quick recording of the new QS content:
ODC-5470-PR

### CODE REVIEW

**Comment by bmignano** [comment]
The updated content and formatting is great, thank you for these changes @serenamarie125 ! LGTM

**Comment by andrewballantyne** [comment]
/retest

Infra issue
> level=fatal msg=Bootstrap failed to complete: failed to wait for bootstrapping to complete: timed out waiting for the condition
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-02-03T18:02:06Z"}
error: failed to execute wrapped command: exit status 1

**Pull request merged**
