### PR TITLE
OCPBUGS-7111: Filter out managed clusters that are not available

### PR DESCRIPTION
**Pull request by TheRealJon**
- Use a common function to list and filter managed clusters. Managed clusters will only be synced if:
  - (new) Available condition is true
  - Product cluster claim is supported
  - Version cluster claim is supported
  - All necessary client configs are present (URL + CABundle)
- Add unit tests for controller util functions
- Remove unused informers from the managed cluster controller (also removes some dependencies)

### CODE REVIEW

**Comment by jhadvig** [comment]
@TheRealJon there are changes in the vendoring files but nochange in the go.mod or go.sum, not sure if you forgot to commit those?

**Comment by TheRealJon** [comment]
> @TheRealJon there are changes in the vendoring files but nochange in the go.mod or go.sum, not sure if you forgot to commit those?

We are not using the ManagedCluster informers anywhere, so I removed all references and re-vendored, so that API got removed from the vendor folder.

**Comment by jhadvig** [comment]
@TheRealJon needs rebase. PTAL

**Comment by jhadvig** [comment]
@TheRealJon pelase rebase this one. Thanks!

**Review by jhadvig — APPROVED** [review]
/lgtm

**Comment by TheRealJon** [comment]
/retest

Unrelated flake:
```
====================================================================================================
  (Run Starting)
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    8.5.0                                                                              │
  │ Browser:    Chrome 102 (headless)                                                              │
  │ Specs:      1 found (e2e/knative-ci.feature)                                                   │
  │ Searched:   features/e2e/knative-ci.feature                                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  e2e/knative-ci.feature                                                          (1 of 1)
Couldn't determine Mocha version
  Logging in as kubeadmin
      Installing operator: "Red Hat OpenShift Serverless"
      Operator Red Hat OpenShift Serverless was not yet installed.
      Installation flow interrupted, check the Installed Operators page for status
  1) "before all" hook for "Create knative workload using Container image with extrenal registry on Add page: KN-05-TC05 (example #1)"
  0 passing (3m)
  1 failing
  1) Perform actions on knative service and revision
       "before all" hook for "Create knative workload using Container image with extrenal registry on Add page: KN-05-TC05 (example #1)":
      Timed out retrying after 100000ms
      + expected - actual
      -'Installing'
      +'Succeeded'
      
      at Object.verifyInstalledOperator (https://console-openshift-console.apps.ci-op-glwxm7pp-be832.origin-ci-int-aws.dev.rhcloud.com/__cypress/tests?p=support/commands/index.ts:58422:12)
      at Context.eval (https://console-openshift-console.apps.ci-op-glwxm7pp-be832.origin-ci-int-aws.dev.rhcloud.com/__cypress/tests?p=support/commands/index.ts:57700:40)
[mochawesome] Report JSON saved to /go/src/github.com/openshift/console/frontend/gui_test_screenshots/cypress_report_knative.json
  (Results)
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        15                                                                               │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      14                                                                               │
  │ Screenshots:  1                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     3 minutes, 3 seconds                                                             │
  │ Spec Ran:     e2e/knative-ci.feature                                                           │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
  (Screenshots)
  -  /go/src/github.com/openshift/console/frontend/gui_test_screenshots/cypress/scree     (1280x720)
     nshots/e2e/knative-ci.feature/Create knative workload using Container image with               
      extrenal registry on Add page KN-05-TC05 (example #1) -- before all hook (faile               
     d).png                                                                                         
  (Video)
  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: /go/src/github.com/openshift/console/frontend/gui_test_scre    (6 seconds)
                          enshots/cypress/videos/e2e/knative-ci.feature.mp4                         
====================================================================================================
  (Run Finished)
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  e2e/knative-ci.feature                   03:03       15        -        1        -       14 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     03:03       15        -        1        -       14  
```

**Pull request merged**
