### PR TITLE
OCPBUGS-28541: Remove Janus IDP and update RHDH quickstarts

### PR DESCRIPTION
**Pull request by jerolimov**
1. Removes the complete Janus IDP Quick starts and the references to Janus IDP from the RHDH quick starts.
2. Added a note that the RHDH Quick start might not be available in the Operator Hub and that users might use the Helm chart instead.

Screenshot of that note (esp. because a `<small>` tag was needed:

image

/cc @vikram-raj @jhadvig @opayne1

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/lgtm

**Comment by jerolimov** [comment]
m)

/retest

**Comment by jerolimov** [comment]
m)

/retest

**Pull request merged**
