### PR TITLE
Bug 1906713: Logged user should be able to get consolequickstarts

### PR DESCRIPTION
**Pull request by jhadvig**
/assign @spadgett

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

I'd expect this to fail CI until we update the test here:

https://github.com/benjaminapetersen/origin/blob/928cc6bb4ef8b257f4529fb009399158157c015c/test/extended/authorization/rbac/groups_default_rules.go#L117

**Comment by jhadvig** [comment]
Fixing the origin tests in https://github.com/openshift/origin/pull/25756

**Comment by spadgett** [comment]
/hold
until openshift/origin#25756 merges

**Comment by andrewballantyne** [comment]
> level=error msg=Error: Request "Create IAM Members roles/compute.instanceAdmin serviceAccount:ci-op-8lq911ct-2f88d-l9s6d-m@openshift-gce-devel-ci.iam.gserviceaccount.com for \"project \\\"openshift-gce-devel-ci\\\"\"" returned error: Error applying IAM policy for project "openshift-gce-devel-ci": Error setting IAM policy for project "openshift-gce-devel-ci": googleapi: Error 400: Service account ci-op-kdsi0d-openshift-m-g9gdk@openshift-gce-devel-ci.iam.gserviceaccount.com does not exist., badRequest

Interesting error... going to retest, not sure why a service account would be unavailable. 
/retest

**Pull request merged**
