### PR TITLE
CONSOLE-3624: Add haproxy timeout annotation to console routes

### PR DESCRIPTION
**Pull request by TheRealJon**
Add 5 minute haproxy timeout annotation to console route to match most browsers' maximum timeout.

### CODE REVIEW

**Comment by periklis** [comment]
LGTM

**Review by jhadvig — CHANGES_REQUESTED** [review]
Thanks @TheRealJon for the PR!
We will need to regenerate the bindata running `make update-bindata-assets`

**Comment by TheRealJon** [comment]
@jhadvig I've updated the bindata

**Comment by TheRealJon** [comment]
QE Approver:
/assign @yanpzhan

**Comment by yanpzhan** [comment]
Launch a cluster against the pr, create a cluster console route, check origin console route and custom console route, both have annotation:
  annotations:
    haproxy.router.openshift.io/timeout: 5m

/label qe-approved

**Pull request merged**
