### PR TITLE
[release-4.11] OCPBUGS-11343: Distinguish between route conditions and remove the old ones

### PR DESCRIPTION
**Pull request by jhadvig**
Backport of:
- https://github.com/openshift/console-operator/pull/735

/assign @TheRealJon

### CODE REVIEW

**Comment by jhadvig** [comment]
```
=== RUN   TestRemoved
    removed_test.go:11: waiting for setup to reach settled state...
    removed_test.go:26: changing console operator state to 'Removed'...
    removed_test.go:27: validating that the operator does not recreate removed resources when ManagementState:Removed...
validating console resources have been removed... true
validating console resources have been removed... true
E0404 14:28:22.626860    9487 request.go:1085] Unexpected error when reading response body: read tcp 10.129.101.135:50664->3.133.228.244:6443: read: connection reset by peer
validating console resources have been removed... false
    removed_test.go:30: unexpected error when reading response body. Please retry. Original error: read tcp 10.129.101.135:50664->3.133.228.244:6443: read: connection reset by peer
    removed_test.go:15: waiting for cleanup to reach settled state...
    console-operator.go:321: waiting for observed generation 32 to match generation 34... 
    console-operator.go:321: waiting for observed generation 32 to match generation 34... 
    console-operator.go:321: waiting for observed generation 32 to match generation 34... 
    console-operator.go:370: waited 10 seconds to reach settled state...
--- FAIL: TestRemoved (222.28s)
```

**Comment by jhadvig** [comment]
flake
/retest

**Comment by yanpzhan** [comment]
Launched a sno cluster containing the pr code, upgraded it to 4.12.0-0.nightly-2023-04-13-061825 successfully. The fix works well.
/label qe-approved
/label cherry-pick-approved

**Comment by jhadvig** [comment]
```
=== RUN   TestEditUnmanagedConfigMap
    unmanaged_test.go:12: waiting for setup to reach settled state...
    unmanaged_test.go:13: changing console operator state to 'Unmanaged'...
    util.go:28: patching Data on the console ConfigMap
    util.go:35: polling for patched Data on the console ConfigMap
    unmanaged_test.go:41: error: timed out waiting for the condition
    unmanaged_test.go:18: waiting for cleanup to reach settled state...
--- FAIL: TestEditUnmanagedConfigMap (15.22s)
```

/retest

**Review by TheRealJon — COMMENTED** [review]
/lgtm

**Comment by sdodson** [comment]
I don't see that this test has ever passed on this PR, are the failures likely to be related to this change or should the test be overridden?

**Comment by jhadvig** [comment]
@sdodson so after checking the must-gather I dont see any correlation between this change and the failures.
For `e2e-aws-console` 99% of running tests are passing. But then it looks like the pod exits all of a sudden.
```
  Running:  dashboards/project-dashboard.spec.ts                                          (18 of 22)
  Project dashboard
  Logging in as kubeadmin
Error: This socket has been ended by the other party
    at TLSSocket.writeAfterFIN [as write] (net.js:456:14)
    at ClientRequest.<anonymous> (/opt/home/.cache/Cypress/8.5.0/Cypress/resources/app/packages/server/node_modules/http-proxy/lib/http-proxy/passes/ws-incoming.js:115:16)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at HTTPParser.execute (<anonymous>:null:null)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
 {
  code: 'EPIPE'
}
Error: This socket has been ended by the other party
    at TLSSocket.writeAfterFIN [as write] (net.js:456:14)
    at ClientRequest.<anonymous> (/opt/home/.cache/Cypress/8.5.0/Cypress/resources/app/packages/server/node_modules/http-proxy/lib/http-proxy/passes/ws-incoming.js:115:16)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at HTTPParser.execute (<anonymous>:null:null)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
error Command failed with exit code 1.
...
+ echo 'Copying artifacts from /go/src/github.com/openshift/console...'
Copying artifacts from /go/src/github.com/openshift/console...
+ cp -r frontend/gui_test_screenshots /logs/artifacts/gui_test_screenshots
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:164","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 3h0m0s timeout","severity":"error","time":"2023-05-31T10:38:08Z"}
{"component":"entrypoint","error":"os: process already finished","file":"k8s.io/test-infra/prow/entrypoint/run.go:242","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Could not interrupt process after timeout","severity":"error","time":"2023-05-31T10:38:08Z"}
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:254","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 15s grace period","severity":"error","time":"2023-05-31T10:38:23Z"}
{"component":"entrypoint","error":"os: process already finished","file":"k8s.io/test-infra/prow/entrypoint/run.go:256","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Could not kill process after grace period","severity":"error","time":"2023-05-31T10:38:23Z"}
{"component":"entrypoint","error":"process timed out","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2023-05-31T10:38:23Z"}
error: failed to execute wrapped command: exit status 127 
INFO[2023-05-31T10:38:24Z] Step e2e-aws-console-test failed after 3h0m45s. 
INFO[2023-05-31T10:38:24Z] Step phase test failed after 3h0m45s.        
INFO[2023-05-31T10:38:24Z] Running multi-stage phase post               
INFO[2023-05-31T10:38:24Z] Running step e2e-aws-console-gather-aws-console. 
INFO[2023-05-31T10:38:39Z] Step e2e-aws-console-gather-aws-console succeeded after 15s. 
INFO[2023-05-31T10:38:39Z] Running step e2e-aws-console-gather-must-gather. 
INFO[2023-05-31T10:40:27Z] Step e2e-aws-console-gather-must-gather succeeded after 1m48s. 
INFO[2023-05-31T10:40:27Z] Running step e2e-aws-console-gather-extra.   
INFO[2023-05-31T10:43:26Z] Step e2e-aws-console-gather-extra succeeded after 2m58s. 
INFO[2023-05-31T10:43:26Z] Running step e2e-aws-console-gather-audit-logs. 
INFO[2023-05-31T10:43:55Z] Step e2e-aws-console-gather-audit-logs succeeded after 29s. 
INFO[2023-05-31T10:43:55Z] Running step e2e-aws-console-ipi-deprovision-deprovision. 
INFO[2023-05-31T10:48:37Z] Step e2e-aws-console-ipi-deprovision-deprovision succeeded after 4m41s. 
INFO[2023-05-31T10:48:37Z] Step phase post succeeded after 10m13s.      
INFO[2023-05-31T10:48:37Z] Releasing leases for test e2e-aws-console    
INFO[2023-05-31T10:48:37Z] Ran for 3h40m32s                             
ERRO[2023-05-31T10:48:37Z] Some steps failed:                           
ERRO[2023-05-31T10:48:37Z] 
  * could not run steps: step e2e-aws-console failed: "e2e-aws-console" test steps failed: "e2e-aws-console" pod "e2e-aws-console-test" failed: could not watch pod: the pod ci-op-jmpdf37j/e2e-aws-console-test failed after 3h0m45s (failed containers: test): ContainerFailed one or more containers exited
Container test exited with code 1, reason Error
```




For `e2e-aws-single-node` I see that the nodes are unable to spin up and some other error msgs:
```
passed: (49.3s) 2023-05-31T07:53:01 "[sig-apps] Job should remove pods when job is deleted [Suite:openshift/conformance/parallel] [Suite:k8s]"
started: (0/63/3119) "[sig-cli] Kubectl client Simple pod should support port-forward [Suite:openshift/conformance/parallel] [Suite:k8s]"
skip [k8s.io/kubernetes@v1.24.0/test/e2e/network/conntrack.go:105]: Test requires >= 2 Ready nodes, but there are only 1 nodes
Ginkgo exit error 3: exit with code 3
```

Retesting to evaluate next step

/retest

**Pull request merged**
