### PR TITLE
CONSOLE-4014: Pass OCM organization ID and OCP cluster ID to console-config.yaml 

### PR DESCRIPTION
**Pull request by jhadvig**
Updating console-operator to get:

- `clusterID` - from the clusterversion `version` resource
- `organizationID` - from the OCM accountmanager API by passing clusterID and pull-secret for `cloud.openshift.com`

Refactored the sync_400 to have a single `GetTelemeterConfiguration` metyod which will be responsible for assembling the telemetry configuration.

Needed to reopen the PR due to [revert](https://github.com/openshift/console-operator/pull/892), which was causing Hypershift issues.

/assign @TheRealJon 

@jerolimov FYI

### CODE REVIEW

**Comment by neisw** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-ovn-bm

**Comment by neisw** [comment]
/payload-aggregate periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn 3

**Comment by jhadvig** [comment]
flakes
/retest

**Comment by jhadvig** [comment]
```
│ ✖  crd-extensions/console-notification      01:27        1        -        1        -        - │
  │    .cy.ts                                                                                      │
```
/retest

**Comment by jhadvig** [comment]
```
crd-extensions/console-yaml-sample.      01:28        1        -        1        -        -   │    cy.ts   
```

/retest

**Comment by jhadvig** [comment]
/payload-aggregate periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn 3

**Review by jerolimov — APPROVED** [review]
Change looks good to me. Please ensure that `/payload-aggregate periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn 3` runs successfully.

/lgtm

**Comment by jerolimov** [comment]
/payload-aggregate periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn 3

**Comment by jhadvig** [comment]
Adding tags manually since the QE already tested the change.

Also discussed the results of the additional TCs with @sjenning https://redhat-internal.slack.com/archives/C01CQA76KMX/p1714665332657349?thread_ts=1714055997.244269&cid=C01CQA76KMX

**Pull request merged**
