### PR TITLE
fix consistency issues with QS displaynames and incorporate highlight…

### PR DESCRIPTION
**Pull request by serenamarie125**
FYI @openshift/quickstart-ux-content 

This fixes https://issues.redhat.com/browse/ODC-5471

Screenshot of the catalog with updated content:
Screen Shot 2021-02-03 at 5 47 34 PM

and individual screenshots of all pages showing hints:
- Monitor
Screen Shot 2021-02-03 at 5 50 24 PM
- Install serverless
Screen Shot 2021-02-03 at 5 50 14 PM
- Install pipelines
Screen Shot 2021-02-03 at 5 50 06 PM
- Getting Started
Screen Shot 2021-02-03 at 5 49 37 PM
- Add health checks 
Screen Shot 2021-02-03 at 5 49 22 PM

### CODE REVIEW

**Comment by bmignano** [comment]
LGTM!

**Comment by serenamarie125** [comment]
@andrewballantyne @spadgett this is the last PR around Quick Starts for me this release :). Brie has tested and provided a LGTM.  If you can provide your magic, that would be great.  Thanks.

**Comment by christianvogt** [comment]
Changes in the diff lgtm. I didn't run them though.

**Comment by andrewballantyne** [comment]
/lgtm

/assign @spadgett 

Need Sam's approval.

**Pull request merged**
