### PR TITLE
OCPBUGS-5420: Back port on-premise host inventory quick start to OCP 4.12.z

### PR DESCRIPTION
**Pull request by chenz4027**
https://issues.redhat.com/browse/OCPBUGS-5420

### CODE REVIEW

**Comment by chenz4027** [comment]
@yanpzhan @jhadvig Could you help review it? It's for backporting the changes made in main (changes in Host inventory and MCE quick starts). Thanks!

**Review by jhadvig — APPROVED** [review]
/lgtm

**Comment by yanpzhan** [comment]
Checked on cluster launched against the pr, the update for Host inventory quickstart works and MCE quick start is added in quick start list.
/label qe-approved
/label cherry-pick-approved

**Pull request merged**
