### PR TITLE
[release-4.13] OCPBUGS-18674: Reset console operator's conditions

### PR DESCRIPTION
**Pull request by TheRealJon**
Manual cherry-pick of https://github.com/openshift/console-operator/pull/796

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/label backport-risk-assessed
/lgtm

**Comment by yanpzhan** [comment]
Built an image against the pr, and launched a 4.12 sno cluster with payload  4.12.0-0.nightly-2024-05-01-172206, disabled console by set "managementState: Removed" in console operator. Then triggered the upgrade to the built image, the upgrade succeeded with no error.
/label qe-approved
/label cherry-pick-approved

**Pull request merged**
