### PR TITLE
OCPBUGS-1708: Set i18n LoadType to Lazy when v1alpha1 i18n annotation is set to false

### PR DESCRIPTION
**Pull request by jhadvig**
/assign @TheRealJon

### CODE REVIEW

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Comment by yapei** [comment]
@jhadvig  does this PR also fix the issue that when `loadType` is set to `Lazy` and consoleplugin is created successfully, it will be automatically reset `loadType` to empty string `""`

=> step1: create a consoleplugin whose `loadType` is set to `Lazy`
```
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: console-demo-plugin
spec:
  backend:
    service:
      basePath: /
      name: console-demo-plugin
      namespace: console-demo-plugin
      port: 9001
    type: Service
  displayName: OpenShift Console Demo Plugin
  i18n:
    loadType: Lazy
  proxy:
    - alias: thanos-querier
      authorization: UserToken
      endpoint:
        service:
          name: thanos-querier
          namespace: openshift-monitoring
          port: 9091
        type: Service
```
=> step2: check consoleplugin metadata
```
$ oc get consoleplugin console-demo-plugin -o json | jq .spec
{
  "backend": {
    "service": {
      "basePath": "/",
      "name": "console-demo-plugin",
      "namespace": "console-demo-plugin",
      "port": 9001
    },
    "type": "Service"
  },
  "displayName": "OpenShift Console Demo Plugin",
  "i18n": {
    **"loadType": ""**
  },
```

**Pull request merged**
