### PR TITLE
ODC-7333: Bump openshift/api to include ConsoleSample CRD

### PR DESCRIPTION
**Pull request by jerolimov**
**Fixes:**
Epic: [ODC-7241: Include Serverless Function Samples in our Sample Catalog](https://issues.redhat.com/browse/ODC-7241) 
Story: [ODC-7333: Update console-operator to latest API to provide the ConsoleSample CRD, add RBAC permissions](https://issues.redhat.com/browse/ODC-7333)

We must update the `openshift/api` dependency to include the new `ConsoleSample` CRD. (see https://github.com/openshift/api/pull/1503)

First commit:

```
go get -u -t github.com/openshift/api
```

And because this automatically updated the `k8s.io/api` from 0.27.1 to 0.27.3 I also updated the other Kubernetes APIs from 0.27.1 to 0.27.3.

```
go get -u -t k8s.io/api@v0.27.3 && \
go get -u -t k8s.io/apiextensions-apiserver@v0.27.3 && \
go get -u -t k8s.io/apimachinery@v0.27.3 && \
go get -u -t k8s.io/client-go@v0.27.3 && \
go get -u -t k8s.io/component-base@v0.27.3 && \
go mod tidy && \
go mod vendor
```

Second commit:

Because `go build` fails with this compiler issue:

```
go build ./cmd/console                                                                      
# k8s.io/client-go/applyconfigurations/meta/v1
vendor/k8s.io/client-go/applyconfigurations/meta/v1/unstructured.go:64:38: cannot use doc (variable of type *"github.com/google/gnostic/openapiv2".Document) as *"github.com/google/gnostic-models/openapiv2".Document value in argument to proto.NewOpenAPIData
# k8s.io/apiserver/pkg/server/routes
vendor/k8s.io/apiserver/pkg/server/routes/openapi.go:46:8: openAPIVersionedService.RegisterOpenAPIVersionedService("/openapi/v2", mux) (no value) used as value
```

I also updated this dependencies:

```
go get -u -t github.com/openshift/library-go/pkg/serviceability@v0.0.0-20230622115850-9596e367bcb4 && \
go get -u -t k8s.io/kube-openapi@v0.0.0-20230501164219-8b0f38b5fd1f && \
go get k8s.io/kube-openapi/pkg/validation/strfmt@v0.0.0-20230501164219-8b0f38b5fd1f && \
go mod tidy && \
go mod vendor
```

And I verified the build with:

```
go build ./cmd/console
```

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by jerolimov** [comment]
@invincibleJai looks like it need to some tests in the origin repo again to get this in :-/

**Review by jhadvig — APPROVED** [review]
Adding labels manually since we are only bumping pkg version

**Pull request merged**
