### PR TITLE
OCPBUGS-11969: Changing  field on any of routes in the openshift-console namespace wont trigger sync loop

### PR DESCRIPTION
**Pull request by jhadvig**
Manual backport of https://github.com/openshift/console-operator/pull/672

/assign @TheRealJon

### CODE REVIEW

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Comment by yapei** [comment]
1. Configure appsDomain value
```
$ oc get ingress.config cluster -o json | jq .spec
{
  "appsDomain": "yapei423test.example.com",
  "domain": "apps.ci-ln-wkv77w2-76ef8.origin-ci-int-aws.dev.rhcloud.com"
}
```
2. remove console routes by setting 
```
$ oc patch console.operator cluster -p '{"spec":{"managementState":"Removed"}}' --type merge
console.operator.openshift.io/cluster patched
$ oc get routes -n openshift-console                                                        
No resources found in openshift-console namespace
```
3. re-create console routes by setting `managedState` to `Managed`
```
$ oc get routes -n openshift-console --watch                                                
NAME        HOST/PORT                                                                                PATH   SERVICES    PORT    TERMINATION          WILDCARD
console     console-openshift-console.apps.ci-ln-wkv77w2-76ef8.origin-ci-int-aws.dev.rhcloud.com            console     https   reencrypt/Redirect   None
downloads   downloads-openshift-console.apps.ci-ln-wkv77w2-76ef8.origin-ci-int-aws.dev.rhcloud.com          downloads   http    edge/Redirect        None
```
even with `appsDomain` configured, `console` and `downloads` route are created with default domain since they are OpenShift core components
the issue is fixed
/label qe-approved
/label cherry-pick-approved

**Pull request merged**
