### PR TITLE
Bug 2009454: Change web terminal subscription permissions from get to list

### PR DESCRIPTION
**Pull request by JPinkney**
This PR is in conjunction with: https://github.com/openshift/console/pull/10045

Signed-off-by: Josh Pinkney <joshpinkney@gmail.com>

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/lgtm
/hold for the frontend review of https://github.com/openshift/console/pull/10045

**Comment by jhadvig** [comment]
@JPinkney in ordeer to merge your PR you need either 
bugzilla/valid-bug label 
OR
docs-approved, px-approved, qe-approved labels.

**Comment by JPinkney** [comment]
@jhadvig I just created the bugzilla and linked it to this PR. Let me know if anything else is needed!

**Pull request merged**
