### PR TITLE
CONSOLE-3278: Add client certificate and key to service monitor

### PR DESCRIPTION
**Pull request by xueqzhan**
Added client certificates based on https://github.com/deads2k/openshift-enhancements/blob/master/enhancements/monitoring/client-cert-scraping.md

### CODE REVIEW

**Comment by jhadvig** [comment]
@xueqzhan thanks for the PR! 
We will need either a BZ or a Jira story in order to merge this one.

**Comment by xueqzhan** [comment]
@jhadvig Sorry for the late response. It turned out kube-rbac-proxy is not coded/configured properly for this yet. So I am working on fixing that first. It does not hurt to get this in. But it will not work with client certificate authentication until kube-rbac-proxy is fixed.

**Comment by jcaianirh** [comment]
@jhadvig @xueqzhan are we targeting 4.12 with this pr or are we moving this to 4.13?

**Comment by xueqzhan** [comment]
> @jhadvig @xueqzhan are we targeting 4.12 with this pr or are we moving this to 4.13?

This PR will not have any effect on the system until the kube-rbac-proxy fix is in. So there is no difference between merging now or later for 4.13.

**Comment by jcaianirh** [comment]
@jhadvig @xueqzhan are we targeting 4.13 with this pr or are we moving this to 4.14?

**Comment by jcaianirh** [comment]
@jhadvig @xueqzhan are we targeting 4.14 with this pr or are we moving this to 4.15?

**Comment by xueqzhan** [comment]
> @jhadvig @xueqzhan are we targeting 4.14 with this pr or are we moving this to 4.15?

We are slowly merging PRs after the long freeze. When things settle down, we should merge this, 4.14 if possible.

**Comment by jhadvig** [comment]
QE Approver: 
/assign @yapei
Docs Approver:
 /assign @opayne1
PX Approver:
/assign @RickJWagner

**Comment by XiyunZhao** [comment]
This PR has been tested in a private build, all metrics are loading as expected
/label qe-approved

**Pull request merged**
