### PR TITLE
CONSOLE-3279: Add node operating systems to console config

### PR DESCRIPTION
**Pull request by TheRealJon**

### CODE REVIEW

**Comment by TheRealJon** [comment]
/hold

Wait for https://github.com/openshift/console-operator/pull/741

**Comment by TheRealJon** [comment]
QE Approver
/assign @yapei

Docs Approver:
/assign @opayne1

PX Approver:
/assign @RickJWagner

**Comment by jhadvig** [comment]
@TheRealJon we need to rebase this one

**Review by jhadvig — APPROVED** [review]
/lgtm
/hold cancel

**Pull request merged**
