### PR TITLE
OCPBUGS-498: Update with latest openshift/api changes

### PR DESCRIPTION
**Pull request by Kartikey-star**
This PR updates the console operator vendor with the latest changes made on openshift/api by 
https://github.com/openshift/api/pull/1213
Signed-off-by: Kartikey Mamgain <mamgainkartikey@gmail.com>

### CODE REVIEW

**Comment by jhadvig** [comment]
@Kartikey-star we will need a jira for this one.

**Comment by Kartikey-star** [comment]
> @Kartikey-star we will need a jira for this one.

https://issues.redhat.com/browse/OCPBUGS-498 is the jira task

**Comment by spadgett** [comment]
We also have #676, so we should coordinate.

cc @debsmita1 @jhadvig

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
