### PR TITLE
CONSOLE-3613: Update vendor bundle after removing multicluster code

### PR DESCRIPTION
**Pull request by TheRealJon**
Follow-on for [CONSOLE-3613](https://issues.redhat.com//browse/CONSOLE-3613) to remove unused "github.com/open-cluster-management/api" dependency

### CODE REVIEW

**Comment by TheRealJon** [comment]
QE Approver
/assign @yanpzhan

px and docs review not needed:
/label px-approved
/label docs-approved

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Comment by jhadvig** [comment]
Adding the label manually since this the change is removing unused dependency

**Pull request merged**
