### PR TITLE
Add ROKS profile annotation to recently added manifests

### PR DESCRIPTION
**Pull request by csrwng**
Adds ROKS profile annotation to recently added manifests (#479)

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve
/retest

**Comment by jhadvig** [comment]
```
error: some steps failed:
  * could not run steps: step e2e-aws-operator failed: "e2e-aws-operator" post steps failed: ["e2e-aws-operator" pod "e2e-aws-operator-gather-must-gather" failed: the pod ci-op-nhy75ljx/e2e-aws-operator-gather-must-gather failed after 11m32s (failed containers: test): ContainerFailed one or more containers exited

Container test exited with code 1, reason Error
---
Running must-gather...
error: gather did not start for pod must-gather-bsn2l: timed out waiting for the condition
error: failed to execute wrapped command: exit status 1
---
Link to step on registry info site: https://steps.ci.openshift.org/reference/gather-must-gather
Link to job on registry info site: https://steps.ci.openshift.org/job?org=openshift&repo=console-operator&branch=master&test=e2e-aws-operator, "e2e-aws-operator" pod "e2e-aws-operator-gather-audit-logs" failed: the pod ci-op-nhy75ljx/e2e-aws-operator-gather-audit-logs failed after 11m34s (failed containers: test): ContainerFailed one or more containers exited

Container test exited with code 1, reason Error
```

/retest

**Comment by jhadvig** [comment]
```
=== RUN   TestRemoved
    removed_test.go:11: waiting for setup to reach settled state...
    removed_test.go:26: changing console operator state to 'Removed'...
    removed_test.go:27: validating that the operator does not recreate removed resources when ManagementState:Removed...
validating console resources have been removed... false
validating console resources have been removed... false
validating console resources have been removed... false
    removed_test.go:30: deleted console Deployment console was recreated:
```

**Pull request merged**
