### PR TITLE
Library go bump

### PR DESCRIPTION
**Pull request by eggfoobar**
Bumping the library-go dependency to latest, this should take advantage of leader election changes for SNO clusters proposed in this [library-go PR](https://github.com/openshift/library-go/pull/1242) and performance improvements in this [PR](https://github.com/openshift/library-go/pull/1235).

Changes:
- updated library-go to use latest `release-4.10` branch
- updated method calls to reflect new method signatures with passed in context
- updated to use new `managementstatecontroller` package instead of old `managementstate` package

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

/assign @yapei
for QE regression test

/label px-approved
/label docs-approved
Dependency bump only, no user-visible changes

**Comment by yapei** [comment]
@XiyunZhao will test and report status back

**Comment by XiyunZhao** [comment]
This PR has been tested and passed. Below listed 4 parts that have been tested, please let me know if any scenario needs more check
1. Pick up cases and do regression test, the base function of console-operator, like edit URL of logout, switch the state of the console-operator to Removed and change back, basic CLI command and etc. are workable and did not find any issue
2. No issue found on the related resources, like pod, deployment, configuration that were created by console-operators
3. No issue found after using different role login to the console, and navigate to related page
4. No issue found on API when trigger upon function test on console (tracking API on the browser development mode)

**Pull request merged**
