### PR TITLE
[release-4.8] Bug 1987315: Bump openshift/api to add missing 'include.release.openshift.io/single-node-developer' annotation to the ConsolePlugin CRD

### PR DESCRIPTION
**Pull request by jhadvig**
API change PR - https://github.com/openshift/api/pull/981

/assign @spadgett

### CODE REVIEW

**Comment by yapei** [comment]
launched a SNO cluster via `cluster-bot`, console-operator is working well, `consoleplugins` CRD has annotation `include.release.openshift.io/single-node-developer: true`

```
$ oc get co
NAME                                       VERSION                                                  AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                             4.8.0-0.ci.test-2021-09-16-060414-ci-ln-vc9tfyb-latest   True        False         False      16m
baremetal                                  4.8.0-0.ci.test-2021-09-16-060414-ci-ln-vc9tfyb-latest   True        False         False      41m
cloud-controller-manager                   4.8.0-0.ci.test-2021-09-16-060414-ci-ln-vc9tfyb-latest   True        False         False      44m
cloud-credential                           4.8.0-0.ci.test-2021-09-16-060414-ci-ln-vc9tfyb-latest   True        False         False      50m
cluster-autoscaler                         4.8.0-0.ci.test-2021-09-16-060414-ci-ln-vc9tfyb-latest   True        False         False      43m
config-operator                            4.8.0-0.ci.test-2021-09-16-060414-ci-ln-vc9tfyb-latest   True        False         False      44m
console                                    4.8.0-0.ci.test-2021-09-16-060414-ci-ln-vc9tfyb-latest   True        False         False      16m

$ oc describe crd consoleplugins.console.openshift.io
Name:         consoleplugins.console.openshift.io
Namespace:    
Labels:       <none>
Annotations:  api-approved.openshift.io: https://github.com/openshift/api/pull/764
              description: Extension for configuring openshift web console plugins.
              displayName: ConsolePlugin
              include.release.openshift.io/self-managed-high-availability: true
              include.release.openshift.io/single-node-developer: true
API Version:  apiextensions.k8s.io/v1
Kind:         CustomResourceDefinition
```

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by spadgett** [comment]
/lgtm cancel

Looks like the `verify` tests are failing.

**Comment by hardys** [comment]
/hold pending fix for the perma-failing verify test

[patch-manager] Not considered for merge this window due to failing test, please remove hold when resolved, thanks!

**Comment by jhadvig** [comment]
Forgot yo run `make update` since the bump also update the `openshift/build-machineery-go`. the test ia passing now

@spadgett @hardys PTAL

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by dhellmann** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.20

picked

**Pull request merged**
