### PR TITLE
OCPBUGS-6488: Recover ConsoleNotificationSync after being degraded

### PR DESCRIPTION
**Pull request by jhadvig**
/assign @TheRealJon

### CODE REVIEW

**Comment by spadgett** [comment]
This is an urgent fix. The following jobs have unrelated failures and have been failing on all PRs. Overriding....

@wking FYI

/override ci/prow/e2e-agnostic-upgrade
/override ci/prow/e2e-gcp-ovn
/override ci/prow/e2e-aws-single-node

**Comment by jhadvig** [comment]
```
clusteroperator/machine-config is not available (Cluster not available for [{operator 4.13.0-0.ci.test-2023-02-01-120409-ci-op-1rt8dckg-latest}]: failed to apply machine config daemon manifests: error during waitForDaemonsetRollout: [timed out waiting for the condition, daemonset machine-config-daemon is not ready. status: (desired: 6, updated: 6, ready: 4, unavailable: 2)]) because Failed to resync 4.13.0-0.ci.test-2023-02-01-120409-ci-op-1rt8dckg-latest because: failed to apply machine config daemon manifests: error during waitForDaemonsetRollout: [timed out waiting for the condition, daemonset machine-config-daemon is not ready. status: (desired: 6, updated: 6, ready: 4, unavailable: 2)]
```
/test e2e-aws-operator

**Pull request merged**
