### PR TITLE
CONSOLE-3912: Add secrets for session encryption/authentication in OIDC

### PR DESCRIPTION
**Pull request by stlaz**
This PR is complementary to the console PR https://github.com/openshift/console/pull/13513 and is built on top of https://github.com/openshift/console-operator/pull/811

/assign @jhadvig 
/cc @spadgett 
/cc @TheRealJon

### CODE REVIEW

**Comment by jhadvig** [comment]
The failing add-flow looks like a flake, although its failing on the [other PR](https://github.com/openshift/console-operator/pull/811) as well.
/retest
/lgtm

**Comment by jhadvig** [comment]
QE Approver:
/assign @yapei
Docs Approver:
/assign @opayne1
PX Approver:
/assign @RickJWagner

**Comment by yanpzhan** [comment]
Regression tests including normal idps test passed on the cluster launched against the pr.

**Comment by yanpzhan** [comment]
For now regression test is acceptable. After discuss with @stlaz , we will have OIDC capabilities test again when we get usable test environment/script.
/label qe-approved

**Comment by jhadvig** [comment]
Adding docs-approval manually since it was added on the https://github.com/openshift/console-operator/pull/811

**Pull request merged**
